/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PaiCoreButton {
        "disabled"?: boolean;
        /**
          * Set up appearance true | false
          * @default true
         */
        "primary": boolean;
        /**
          * Set the value
          * @default "Button"
         */
        "value"?: string;
    }
}
declare global {
    interface HTMLPaiCoreButtonElement extends Components.PaiCoreButton, HTMLStencilElement {
    }
    var HTMLPaiCoreButtonElement: {
        prototype: HTMLPaiCoreButtonElement;
        new (): HTMLPaiCoreButtonElement;
    };
    interface HTMLElementTagNameMap {
        "pai-core-button": HTMLPaiCoreButtonElement;
    }
}
declare namespace LocalJSX {
    interface PaiCoreButton {
        "disabled"?: boolean;
        /**
          * Set up appearance true | false
          * @default true
         */
        "primary"?: boolean;
        /**
          * Set the value
          * @default "Button"
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "pai-core-button": PaiCoreButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pai-core-button": LocalJSX.PaiCoreButton & JSXBase.HTMLAttributes<HTMLPaiCoreButtonElement>;
        }
    }
}
